// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAleQacxZRo3X0iLiEpLW6hEY-6QtlsuG8',
    appId: '1:848503255516:web:36484d87606d5c04931f19',
    messagingSenderId: '848503255516',
    projectId: 'chat-8b337',
    authDomain: 'chat-8b337.firebaseapp.com',
    storageBucket: 'chat-8b337.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUo_oW4tS3X-XJ_s1jd4Gxjb4uSdWZ_vw',
    appId: '1:848503255516:android:9ad5f25e9d5a87be931f19',
    messagingSenderId: '848503255516',
    projectId: 'chat-8b337',
    storageBucket: 'chat-8b337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVoO83dn-76O42gS4c4xvweUYAyS26lkw',
    appId: '1:848503255516:ios:8ca34a5be544aa92931f19',
    messagingSenderId: '848503255516',
    projectId: 'chat-8b337',
    storageBucket: 'chat-8b337.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVoO83dn-76O42gS4c4xvweUYAyS26lkw',
    appId: '1:848503255516:ios:8ca34a5be544aa92931f19',
    messagingSenderId: '848503255516',
    projectId: 'chat-8b337',
    storageBucket: 'chat-8b337.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
